workflows:
  flutter-build:
    name: Flutter Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest  # Needed if you build for iOS
      vars:
        FIREBASE_CLI_TOKEN: EncryptedOrEnvVariable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Flutter Build APK
        script: |
          flutter build apk --release
      - name: Flutter Build iOS (optional, only if targeting iOS)
        script: |
          flutter build ipa --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - omkarmalve1701@gmail.com
        notify:
          success: true
          failure: true
